### ISSUE TITLE
部署

### ISSUE THREAD

**Issue by sakonohana** [shuxuecode/House#3]
我想知道这个怎么部署啊？

**Comment by shuxuecode** [comment]
分别是两个工程，springboot-house是后台，可以使用tomcat部署，miniapp-house是小程序代码，参考微信官方文档部署

**Comment by sakonohana** [comment]
我的服务通过
(10条消息) 在eclipse中如何导入springboot项目_飞奔的波大爷的博客-CSDN博客_eclipse导入springboot项目


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shuxuecode/House"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月5日(星期三) 中午12:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shuxuecode/House] 部署 (Issue #3)





 
分别是两个工程，springboot-house是后台，可以使用tomcat部署，miniapp-house是小程序代码，参考微信官方文档部署
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sakonohana** [comment]
我的服务通过
(10条消息) 在eclipse中如何导入springboot项目_飞奔的波大爷的博客-CSDN博客_eclipse导入springboot项目
这个启动起来了但是------------------ 原始邮件 ------------------


这个状态，也无法登录，我也不知道怎么修改
发件人:                                                                                                                        "shuxuecode/House"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月5日(星期三) 中午12:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shuxuecode/House] 部署 (Issue #3)





 
分别是两个工程，springboot-house是后台，可以使用tomcat部署，miniapp-house是小程序代码，参考微信官方文档部署
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
